  name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt5 opencv-python numpy

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name Tracking_Pro tracking_pro.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Tracking_Pro_exe
          path: dist/Tracking_Pro.exe
